sudo: required
dist: trusty
addons:
  apt:
    update: true
before_install:
- "./scripts/setup.sh"
script:
- "./scripts/build.sh"
deploy:
  provider: pages
  lacal-dir: pages
  github-token:
    secure: PD23cZrwELNm4aYWOx1Vf7q0Zd+tzPt2QKjGsOcmGOEbJM8UaSzy2ApGCKQOMMmld104GS02cN4drCRCfEdDehSyNMfkVo5Idm7KjuFe1N+zmmZURpwKq6wfJ2MrBX18QmumKKyf5X8+hg99G20FiYGVhVRMzlnyvXTL1SJelaXHSYZhHZJ+VwOjmazcBRBOKOHvenN8Pw/K0wMmukYs8xb5l9zDSzT5gOyPP2vkaEWRX8bER0d0C5aZmH/vt1XLdWwPMjEB5jY9cLZTEPBpdEzyifBVYe4ehXz3YDRbLLUW+RmMslJCd0WMvzf0w/yXiKu9cmjRC3TeoNkOZjpfd2ndmLpcUyFwLp1Cka8jM/R9LBJYmLCOwOZhWI/ycZJCjYAbJkxOoUx9FXlPBAx9Wm34reF/0//+KbNlkg5G0IaIsP6d+r3DXe2PNDxUsPbPYIfTf6/QWSVZJDWsU4pkLTaPdNYXuEz8yLbAmu9Gk9wsXYt/3FnowbnslUj2wxP96urhy1CrW8oA/eRTuHWvP1K7vmbDmfo96arthB+v2XNfuHTho5k3W4D2gv05OXFh86r2qIiCSlbqocJfOupCJQ/KzbiDB8zBKu34aSopyqFKPfMDWSCc/WtVWxDeh10p1e3dOZYaroN92I+c1jzTlb2PFNN0p1O2Pk37lCKGCHI=
  keep-history: true
  skip_cleanup: true
  on:
    branch: master
  
